### ISSUE TITLE
findOrCreate not working

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback-connector-postgresql#107] opened 2015-09-01 09:47 UTC
no matter what where clause I give, it always returns the first row as it was found in the database.

e.g:
User.findOrCreate({username : 'aaaa'}, user, userCallback);

returns:

``` javascript
{ __cachedRelations: {},
  __data: 
   { realm: null,
     username: 'eyal.gruber',
     password: '$2a$10$/ObfdeYHYSH2edI26O9g8.aLsCeVua3VnSS2EBBhPK67cRyLVlqDW',
     credentials: null,
     challenges: null,
     email: 'eyal.gruber@intel.com',
     emailVerified: null,
     verificationToken: null,
     status: null,
     created: null,
     lastUpdated: null,
     id: 1 },
  __dataSource: undefined,
  __strict: false,
  __persisted: true 
}
```

**Comment by raymondfeng** [comment] 2015-09-01 15:28
Can you run with `DEBUG=loopback:connector:postgresql node .` to see what SQL statements are executed? I cannot reproduce the problem locally.

**Comment by ezraroi** [comment] 2015-09-01 19:23
sure, will update tomorrow

**Comment by ezraroi** [comment] 2015-09-02 06:07
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:54 GMT loopback:connector:postgresql SQL: SELECT "name","id" FROM "public"."sites" ORDER BY "id" LIMIT 1
Wed, 02 Sep 2015 06:06:55 GMT loopback:connector:postgresql {"command":"SELECT","rowCount":1,"oid":null,"rows":[{"name":"iil","id":1}],"fields":[{"name":"name","tableID":4113113,"columnID":1,"dataTypeID":1043,"dataTypeSize":-1,"dataTypeModifier":1028,"format":"text"},{"name":"id","tableID":4113113,"columnID":2,"dataTypeID":23,"dataTypeSize":4,"dataTypeModifier":-1,"format":"text"}],"_parsers":[null,null],"rowAsArray":false}
Wed, 02 Sep 2015 06:06:55 GMT loopback:connector:postgresql {"command":"SELECT","rowCount":1,"oid":null,"rows":[{"name":"iil","id":1}],"fields":[{"name":"name","tableID":4113113,"columnID":1,"dataTypeID":1043,"dataTypeSize":-1,"dataTypeModifier":1028,"format":"text"},{"name":"id","tableID":4113113,"columnID":2,"dataTypeID":23,"dataTypeSize":4,"dataTypeModifier":-1,"format":"text"}],"_parsers":[null,null],"rowAsArray":false}

**Comment by ezraroi** [comment] 2015-09-02 06:08
Looks like it is not taking into account the first parameter I pass to it that includes the wehere

Site.findOrCreate({name : site.name}, site, siteCallback);

**Comment by raymondfeng** [comment] 2015-09-02 19:36
What version of `loopback-connector-postgresql` and `loopback-connector` do you have?

**Comment by ezraroi** [comment] 2015-09-02 19:57
"loopback-connector-postgresql": "^2.3.0"
I don't have direct dependency on `loopback-connector` in my package.json

I will try but i am not sure I will have time in the following weeks as I am travelling tomorrow for 3 weeks

**Comment by ezraroi** [comment] 2015-09-02 20:01
This is my package.json
```javascript
"dependencies": {
    "async": "^1.4.2",
    "body-parser": "^1.13.2",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "javascript-state-machine": "^2.3.5",
    "loopback": "^2.14.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-storage": "^1.5.1",
    "loopback-connector-postgresql": "^2.3.0",
    "loopback-connector-sendgrid": "^1.1.4",
    "loopback-datasource-juggler": "^2.39.0",
    "morgan": "^1.6.1",
    "q": "^1.4.1",
    "serve-favicon": "^2.0.1",
    "underscore": "^1.8.3",
    "winston": "^1.0.1"
  }
```

**Comment by erikverheij** [comment] 2015-09-09 17:07
I'm having the same problem with the mysql connector.

````
    "loopback": "^2.22.0",
    "loopback-boot": "^2.12.2",
    "loopback-connector-mysql": "^2.2.0",
    "loopback-datasource-juggler": "^2.39.0",
```

**Comment by PowerP** [comment] 2015-10-11 20:01
Hi,

was struggling with the same and found the problem. 
Documentation says: PersistedModel.findOrCreate(where, data, callback)

so I expected this:

```
User.findOrCreate({
          email: email
      },  [...]
```

This returns the first row as reported.
To solve this u have to use:

```
User.findOrCreate({
        where:{
          email: email
        }
      }, [...]
```

**Comment by raymondfeng** [comment] 2015-10-11 20:25
I'll check the code.

**Comment by doublemarked** [comment] 2015-11-20 14:25
I believe this is caused by incorrect documentation - see the following: https://github.com/strongloop/loopback-datasource-juggler/issues/766

**Comment by drmikecrowe** [comment] 2016-01-31 15:43
Confirmed -- still an issue

**Comment by ssh24** [comment] 2017-06-23 03:06
The reason behind the issue was incorrect documentation for `findOrCreate`. See [issue](https://github.com/strongloop/loopback-datasource-juggler/issues/766).

It should be resolved now with the fix on the [findOrCreate docs](https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate). Closing this. Feel free to reopen if needed.

**Closed by ssh24** 2017-06-23 03:06 UTC
Labels: apex, triaging
