### ISSUE TITLE
typecast date/time types to text in query

### ISSUE THREAD

**Issue by ptrblgh** [strongloop/loopback-connector-postgresql#247] opened 2017-04-19 11:32 UTC
I have a datatable and a text input filed. The expected behaviour would be to perform a search on postgresql table fields (including the timestamp ones, in this example: stamp).
I use loopback's where filter's like operator. But unfortunetly a cast would be necessary on the table's field (stamp::TEXT) to make it work.

the model's property:
```json
"stamp": {
      "type": "String",
      "required": true,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "stamp",
        "dataType": "timestamp with time zone",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    },
```

the url:
`http://localhost:3000/api/users?filter[where][stamp][like]=2017`

the error:
```
length: 213
severity: ERROR
code: 42883
hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
position: 246
file: parse_oper.c
line: 766
routine: op_error
error: operator does not exist: timestamp with time zone ~~ text
    at Connection.parseE (...node_modules\pg\lib\connection.js:569:11)
    at Connection.parseMessage (...node_modules\pg\lib\connection.js:396:17)
    at Socket. (..node_modules\pg\lib\connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

the working query would be:
`select stamp from du_user where stamp::text like '%2017%'`

Right now i don't have any idea how to achieve a query like that with loopback/loopback-connector-postgresql. 
Any suggestions/help would be appreciated.

**Comment by ptrblgh** [comment] 2017-04-19 14:03
I think i have found a solution.

As the postgres documentations says: 
>The LIKE expression returns true if the ***string*** is contained in the set of strings represented by pattern.

Therefore typecasting to text explicitly the target column not result any error.

The following lines should be changed:
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L429
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L432
https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L435https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L438

e.g.: L429 change:
from: ```return new ParameterizedSQL(columnName + " LIKE ? ESCAPE E'\\\\'"```
to ```return new ParameterizedSQL(columnName + "::TEXT LIKE ? ESCAPE E'\\\\'"```

Contributor opinions?

**Comment by ssh24** [comment] 2017-05-05 15:17
@ptrblgh I am not sure what the issue is. Currently the code does not cast it into a string before using a `like`/`nlike` operator. 

Without the casting it works fine for me. Tested using the latest postgresql, `v3.0.0`.

**Model definition:**
```json
{
  "name": "Expense",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "Description": {
      "type": "string"
    },
    "Amount": {
      "type": "number",
    },
    "Stamp": {
      "type": "string",
      "postgresql": {
        "columnName": "stamp",
        "dataType": "timestamp with time zone",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Boot script:**
```javascript
'use strict';
var async = require('async');

module.exports = function(app) {
  var postgresDs = app.dataSources.postgresDs;
  var Expense = app.models.Expense;

  postgresDs.automigrate(function(err, result) {
    if (err) throw err;
    Expense.create([
      {
        Description: 'Expense 1',
        Amount: 12,
        Stamp: '1999-01-08 12:25:00',
      },
    ], function(err, result) {
      if (err) throw err;
      Expense.find({where: {Stamp: {like: '1999%'}}}, function(err, result) {
        if (err) throw err;
        console.log('Result: ' + JSON.stringify(result));
      });
    });
  });
};
```

The output is as expected:
```bash
Result: [{"Description":"Expense 1","Amount":12,"Stamp":"1999-01-08 12:25:00","id":1}]
```

**Comment by ptrblgh** [comment] 2017-05-05 18:34
the postgresql command line gives this error:

```
db=# select stamp from user where stamp LIKE '%2017%';
ERROR:  operator does not exist: timestamp with time zone ~~ unknown
LINE 1: select stamp from user where stamp LIKE '%2017%';
                                              ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.```

postgresql version: 8.4.22

**Comment by ssh24** [comment] 2017-05-05 20:26
@ptrblgh Right. It looks like I was reproducing with your solution, and hence it worked for me. Do you mind submitting a PR to fix this issue?

**Comment by ptrblgh** [comment] 2017-05-06 06:23
Yes, of course.

**Comment by ssh24** [comment] 2017-05-29 01:06
Closing this. Issue fixed https://github.com/strongloop/loopback-connector-postgresql/pull/255

Thank you @ptrblgh for the contribution!

**Closed by ssh24** 2017-05-29 01:06 UTC
Labels: apex, bug, patch-welcome
