### ISSUE TITLE
`pg@^6.x` is not `node@<=0.12` compatible.

### ISSUE THREAD

**Issue by pthieu** [strongloop/loopback-connector-postgresql#149] opened 2016-07-11 22:26 UTC
Need to add a shim: https://github.com/brianc/node-pg-pool#bring-your-own-promise
and issue was tracked here: https://github.com/brianc/node-postgres/issues/1066

Was upgraded here: https://github.com/strongloop/loopback-connector-postgresql/pull/143

**Comment by 0candy** [comment] 2016-10-04 19:07
Should be fixed with https://github.com/strongloop/loopback-connector-postgresql/pull/166

Please let us know if the issue is not resolved and we can reopen this. Thanks!

**Closed by 0candy** 2016-10-04 19:07 UTC
