### ISSUE TITLE
using upsert will trigger loopback hook twice if it's a new instance

### ISSUE THREAD

**Issue by tmclouisluk** [strongloop/loopback-connector-postgresql#209] opened 2017-02-10 08:42 UTC
```
MyModel.observe('before save', function (ctx, next) {
  if (ctx.isNewInstance) {
    console.log("new");
  } else {
    console.log("update");
  }
  next();
});
```
If it's updating the model, the console will show "update" once while if it's creating a new model, the console will show "new" twice.
No matter I use "after save" or etc hooks.

**Comment by ssh24** [comment] 2017-07-19 01:43
@tmclouisluk It logged **new** twice probably because you had 2 instances of the model created. The before hook is called for **every instance** created. Hence, if you created x instances of the model, it would print **new** x times.

On the other hand for `update` it is different. The before save hook is called once for **each update call** and the update (which could be bulk or a single update) is done by the respective connector.

Here is a sample reproduction:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo',
            age: 1
        }, {
            name: 'Bar',
            age: 1
        }, {
            name: 'Baz'
        }, {
            name: 'Sam'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            Employee.update({age: 1}, {name: 'Foo', age: 12}, function(err, result) {
                if (err) throw err;
                console.log('\nUpdated instance 1st time: ' + util.inspect(result));

                Employee.update({name: 'Foo'}, {age: 14}, function(err, result) {
                    if (err) throw err;
                    console.log('\nUpdated instance 2nd time: ' + util.inspect(result));
                    
                    Employee.find(function(err, result) {
                    if (err) throw err;
                    console.log('\nFound instance: ' + util.inspect(result));
                    });
                });
            });
        });
    });

    Employee.observe('before save', function (ctx, next) {
        if (ctx.isNewInstance) {
            console.log(">> hook output: new");
        } else {
            console.log(">> hook output: update");
        }
        next();
    });
};
```

**output**
```bash
sakibs-mac:postgresql-209 ssh$ node .
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

Automigrate completed
>> hook output: new
>> hook output: new
>> hook output: new
>> hook output: new

Created instance: [ { name: 'Foo', age: 1, id: 1 },
  { name: 'Bar', age: 1, id: 2 },
  { name: 'Baz', id: 3 },
  { name: 'Sam', id: 4 } ]
>> hook output: update

Updated instance 1st time: { count: 2 }
>> hook output: update

Updated instance 2nd time: { count: 2 }

Found instance: [ { name: 'Foo', age: 14, id: 1 },
  { name: 'Foo', age: 14, id: 2 },
  { name: 'Baz', age: null, id: 3 },
  { name: 'Sam', age: null, id: 4 } ]
```

Hopefully this answers your question. Closing this issue. Feel free to reopen if needed.

**Closed by ssh24** 2017-07-19 01:43 UTC
Labels: team-apex
