### ISSUE TITLE
How to use custom schema in loopback 4 cli

### ISSUE THREAD

**Issue by MrJim-06** [strongloop/loopback-connector-postgresql#362] opened 2019-02-14 07:47 UTC
**I'm use this code to use custom schema in todo.model.ts file**
```typescript
import { Entity, model, property } from '@loopback/repository';

@model({ options: { postgresql: { schema: 'testschema' } } })
export class Todo extends Entity {
  @property({
    type: 'number',
    id: true,
  })
  id?: number;

  @property({
    type: 'string',
    required: true,
  })
  title: string;

  @property({
    type: 'string',
    required: true,
  })
  author: string;

  @property({
    type: 'string',
    required: true,
  })
  description: string;

  @property({
    type: 'boolean',
  })
  isComplete?: boolean;


  constructor(data?: Partial<Todo>) {
    super(data);
  }
}

```
**this is error**

```
Unhandled error in GET /todos: 500 error: relation "public.todo" does not exist
    at Connection.parseE (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:555:11)
    at Connection.parseMessage (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:380:19)
    at Socket.<anonymous> (C:\Users\develop\Desktop\test-project\loopback-postgres\node_modules\pg\lib\connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by dhmlau** [comment] 2019-02-15 01:46
@MrJim-06 , i'm closing this issue as duplicate of https://github.com/strongloop/loopback-next/issues/2388.  I've answered your question in that issue already, PTAL. Thanks.

**Closed by dhmlau** 2019-02-15 01:46 UTC

**Comment by k3n3l** [comment] 2019-02-19 00:24
Hi, you could try with:

`@model({settings: {postgresql: {schema: 'testschema'}}})`
