### ISSUE TITLE
Discovery broken in 3.0?

### ISSUE THREAD

**Issue by bdharrington7** [strongloop/loopback-connector-postgresql#236] opened 2017-04-06 17:21 UTC
# Description/Steps to reproduce
I was using the 2.8.0 version of the connector to play with the discovery functionality, with code something like this: 

```js
ds.discoverAndBuildModels('worlds', {schema: 'public', relations: true},
function (err, schemas) {
  if (schemas) {
    console.log(schemas)
    Object.keys(schemas).forEach(function(key) {
      console.log('working on', key);

     // more stuff here, not really relevant

      fs.writeFile(outputFile, JSON.stringify(schema, null, 2), function(err) {
        if (err) {
          console.log ('Error:', err);
        } else {
          console.log('Writing', outputFile, 'successful');
        }
      })
    })
  } else {
    console.log ('No schemas found')
    process.exit();
  }
});
```
When I upgraded to 3.0.0 of this connector, nothing would come back, I would just get the message "No schemas found"

# Additional information
Platform: darwin 
Arch: x64 
node version: 6.9.4

$   npm ls --prod --depth 0 | grep loopback
hello-postgres-loopback@1.0.0 /Users/brian/bbs/sandbox/hello-postgres-loopback
├── loopback@3.6.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-postgresql@2.8.0

**Comment by bdharrington7** [comment] 2017-04-06 18:33
Possibly related to #135

**Comment by ssh24** [comment] 2017-04-20 18:24
@bdharrington7 Just wondering while I am trying to reproduce your issue. On your code, what happens when you put a `if (err) console.log(err)` before the `if (schemas)` block?

**Comment by ssh24** [comment] 2017-04-20 19:06
**Script**:
```javascript
// Discover and build models from books table
ds.discoverAndBuildModels('books', {schema: 'public', relations: true}, function(err, schemas) {
  if (err) console.log('Err: ' + err);
  if (schemas) {
    Object.keys(schemas).forEach(function(key) {
      console.log('working on', key);
    });
  }
});
```

**Output on v3.0.0**:
```
sakibs-mac:postgresql-issue-236 ssh$ node server/boot/script.js
working on Books
```

**Output on v2.8.0**:
```
sakibs-mac:postgresql-issue-236 ssh$ node server/boot/script.js
working on Books
```

@bdharrington7 I am unable to reproduce this issue. Could you please let me know what **juggler, connector, node, npm and slc** version you are using?

These are the version that this was reproduced against:
```
sakibs-mac:postgresql-issue-236 ssh$ npm list loopback-datasource-juggler
postgresql-issue-236@1.0.0 /Users/ssh/workspace/apic loopback/slc/2017/apr17/postgresql-issue-236
└─┬ loopback@3.6.17
  └── loopback-datasource-juggler@3.5.13

sakibs-mac:postgresql-issue-236 ssh$ npm list loopback-connector
postgresql-issue-236@1.0.0 /Users/ssh/workspace/apic loopback/slc/2017/apr17/postgresql-issue-236
└─┬ loopback@3.6.17
  └─┬ loopback-datasource-juggler@3.5.13
    └── loopback-connector@4.2.5

sakibs-mac:postgresql-issue-236 ssh$ node -v
v4.4.3
sakibs-mac:postgresql-issue-236 ssh$ npm -v
3.10.10
sakibs-mac:postgresql-issue-236 ssh$ slc -v
strongloop v6.0.3 (node v4.4.3)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.1 (249315b)
├── strong-pm@5.2.4
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.2 (4b9dde0)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.5 (16841d6)
└── nodefly-register@0.3.3
```

**Comment by ssh24** [comment] 2017-04-24 16:35
@bdharrington7 Closing this issue as it is not reproducible as a bug. Feel free to reopen it if needed.

**Closed by ssh24** 2017-04-24 16:35 UTC
Labels: apex, blocked, p1
