### ISSUE TITLE
Geopoint: lat and lng inverted!

### ISSUE THREAD

**Issue by radar155** [strongloop/loopback-connector-postgresql#121] opened 2015-12-26 21:09 UTC
I'm using postgresql 9.4

I have a model with a geopoint property. When i save an istance, doing something like :

``` javascript
Mymodel.create({geopoint: loopback.GeoPoint({lat: 44.44, lng: 25.25})}, function(err, istance){
    console.log(istance);
});
```

the log is:

``` javascript
{geopoint: GeoPoint: {lat: 44.44, lng:25.25}}
```

All seems ok, the problem is that if i try to call find() on my model, the istance has latitude and longitude inverted, so:

``` javascript
Mymodel.find(function(err, istance){
    console.log(istance);
});
```

the log is:

``` javascript
{geopoint: {lat: 25.25, lng:44.44}}
```

This happen also if i do the same query from client side using the angular lb-services. And this happen also if, when creating the istance, i write something like:

``` javascript
Mymodel.create({geopoint: {lat:44.44, lng:25.25}})
```

(note that i'm not calling loopback.GeoPoint but i'm simply passing an object with latitude and longitude)

Using psql from command line, 
**select geopoint from public.mymodel** returns:
**(25.25, 44.44)**

Note that the first value is the original longitude and the second is the latitude.

I can't figure if i'm mistaking something or if there is some bug.

in Mymodel.json, ofcourse, the datatype of the property geopoint is "geopoint".

I hope anyone will help me to understand what is happening!

**Comment by RudthMael** [comment] 2016-07-22 15:43
I'm encountering the same problem:

@channel: Quelqu’un peut m’expliquer ?
```
loopback > Driver.findById('9O3vlWWduoRYlBLhp4PUG1~t’)
loopback > d.location
{ lng: 2.3332335, lat: 48.8816597 }
```

When I hit the API, I get:
```
location: {
  lng: 48.9494163,
  lat: 2.3314704
},
```

**Comment by 0candy** [comment] 2016-10-13 22:02
@radar155 Could you provide a sample repo to reproduce this issue? 
http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by ponomarenkotema** [comment] 2016-12-20 13:59
Hi, I have got the same problem. When it going to be fixed?

**Comment by emresebat** [comment] 2017-01-24 11:53
Hi

The problem seems to be caused by toColumnValue function.

https://github.com/strongloop/loopback-connector-postgresql/blob/a7c22cfa116ab52919c599bd890dffbd681d755f/lib/postgresql.js#L493-L502

The comment says 
 // Postgres point is point(lng, lat)
but I'm not sure about that. Normally x is lat, y is lng. The problem is you're providing the lat,lng as xiy but during storage these are converted.

Also in the fromColumnValue function the same logic is applied

https://github.com/strongloop/loopback-connector-postgresql/blob/a7c22cfa116ab52919c599bd890dffbd681d755f/lib/postgresql.js#L259-L278

Can anyone point to a reference that this is the correct way to convert to Point?

**Comment by emresebat** [comment] 2017-01-24 12:22
Hi

Answering my own question, so yes that's the correct way to store for PostGIS. Mapping frameworks use Lat/Lon but spatial databases use Lon/Lat. 

Here is a [reference](http://postgis.net/2013/08/18/tip_lon_lat/)

**Comment by ssh24** [comment] 2017-06-22 19:48
Can confirm this is not an issue anymore on the latest connector. 

Postgresql stores spatial coordinates in the form of `(lng, lat)`.

Here is a sample snippet:

**model-definition.json**
```json
{
  "name": "Business",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "required": true,
      "id": true
    },
    "name": {
      "type": "string"
    },
    "location": {
      "type": "geopoint"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var Business = app.models.Business;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Business.create([{
            id: 1,
            name: 'Foo Inc.',
            location: {
                lat: 27.456,
                lng: -23.944
            }
        }, {
            id: 2,
            name: 'Bar Inc.',
            location: {
                lat: -37.456,
                lng: 25.944
            }
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreate instance: ' + util.inspect(result));

            Business.find(function(err, result) {
                if (err) throw err;
                console.log('\nFound instance: ' + util.inspect(result));
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:postgresql-121 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Create instance: [ { id: 1,
    name: 'Foo Inc.',
    location: GeoPoint { lat: 27.456, lng: -23.944 } },
  { id: 2,
    name: 'Bar Inc.',
    location: GeoPoint { lat: -37.456, lng: 25.944 } } ]

Found instance: [ { id: 1,
    name: 'Foo Inc.',
    location: { lng: -23.944, lat: 27.456 } },
  { id: 2,
    name: 'Bar Inc.',
    location: { lng: 25.944, lat: -37.456 } } ]
```

As you can see it does not matter in which order you specify the `lat` or `lng` using the connector, it always stores it in the database as `(lng, lat)`. And upon find operation, it returns the exact order the database stores it as.

Closing this issue as resolved. Feel free to reopen if needed.

**Closed by ssh24** 2017-06-22 19:48 UTC
Labels: apex, triaging
