### ISSUE TITLE
timestamp issue with postgresql9.5 version

### ISSUE THREAD

**Issue by Jayaseelan-Vaiyapuri** [strongloop/loopback-connector-postgresql#271] opened 2017-07-10 12:54 UTC
Hi,

Am gettingdifferent output for _createdon field after posting the date on Explorer. Is there any fix available?

Post Respone in Explorer : "_createdOn": "2017-07-10T12:35:28.530Z"
DB Value in postgresql    :  "_createdon": 2017-07-10 18:05:28.53+05:30"
Get Response in Explorer:  "_createdOn": "2017-07-10T07:05:28.000Z",

Any idea how to fix  this issue?

Regards
Jayaseelan

**Comment by ssh24** [comment] 2017-07-11 02:31
@Jayaseelan-Vaiyapuri What version of the postgresql connector module are you using?

**Comment by Jayaseelan-Vaiyapuri** [comment] 2017-07-11 03:40
Hi,

I am using "version": "0.9.0-beta"

Thnx

**Comment by ssh24** [comment] 2017-07-11 17:57
I cannot reproduce this issue with postgresql@2.7.0

- Did a post request
```json
{
  "name": "string",
  "dateJoined": "2017-07-10T12:35:28.530Z"
}
```

- Post request response
```json
{
  "name": "string",
  "dateJoined": "2017-07-10T12:35:28.530Z",
  "id": 3
}
```

- Get request response
```json
[
  {
    "name": "Foo",
    "dateJoined": "2017-07-11T17:48:01.359Z",
    "id": 1
  },
  {
    "name": "Bar",
    "dateJoined": "2016-05-10T00:00:00.000Z",
    "id": 2
  },
  {
    "name": "string",
    "dateJoined": "2017-07-10T12:35:28.530Z",
    "id": 3
  }
]
```

**Comment by ssh24** [comment] 2017-07-17 20:57
Closing this as it is not an issue. Feel free to reopen if needed.

**Closed by ssh24** 2017-07-17 20:57 UTC
Labels: team-apex, triaging
