### ISSUE TITLE
Fix CI for Node.js 10: 

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-postgresql#384] opened 2019-07-09 16:31 UTC
See comment: 
https://github.com/strongloop/loopback-connector-postgresql/pull/383#issuecomment-509157437 (failed on Node.js 10)
https://github.com/strongloop/loopback-connector-postgresql/pull/385 (failed on Node.js 12)

```
1) autoupdate
     foreign key constraint
       should create, update, and delete foreign keys:
   error: duplicate key value violates unique constraint "pg_namespace_nspname_index" (while running initial autoupdate)
    at Connection.parseE (node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:22)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```
## Acceptance Criteria
- [ ] fix the CI failure

**Comment by jannyHou** [comment] 2019-07-09 19:02
probably caused by the broken jsdoc, CI is green for PR https://github.com/strongloop/loopback-connector-postgresql/pull/385 now.

**Comment by jannyHou** [comment] 2019-07-09 19:09
Closing after #385 landed.

**Closed by jannyHou** 2019-07-09 19:09 UTC
Labels: 2019Q3, ci
