### ISSUE TITLE
Transactions are broken on v3.0.1

### ISSUE THREAD

**Issue by StevenWinde** [strongloop/loopback-connector-postgresql#258] opened 2017-05-15 19:03 UTC
# Description/Steps to reproduce
This works fine in 3.0.0 but not in 3.0.1
```
this.beginTransaction( 'READ COMMITTED', ( err, tx )=>{
  this.updateAll( { foo: 'bar' },  { foo: 'bar2'},  { transaction: tx },
  ( err )=>{
    // err is Transaction is not active.
  }
}
```

**Comment by cadesalaberry** [comment] 2017-05-18 09:18
Version 3.0.1 is also not working for me...

Do not use this version in production !

```
Error: Transaction is not active
at /opt/app/node_modules/loopback-connector-postgresql/lib/postgresql.js:205:18
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickDomainCallback (node.js:390:13)
From previous event:
  at Object.createPromiseCallback (/opt/app/node_modules/loopback-datasource-juggler/lib/utils.js:492:17)
  at Function.DataAccessObject.update.DataAccessObject.updateAll (/opt/app/node_modules/loopback-datasource-juggler/lib/dao.js:2551:20)
```

**Comment by jmls** [comment] 2017-06-25 11:41
_really_ ? transactions are broken, and no-one from SL responds ? It's this sort of thing that really makes me worry about strongloop. Does anyone have a fix ?

**Comment by cadesalaberry** [comment] 2017-06-25 18:15
@bajtos could you have a look at it please ?

**Comment by bajtos** [comment] 2017-06-26 13:11
Hello, I am not familiar with PostgreSQL myself. The connector version 3.0.1 contains the following changes (see https://github.com/strongloop/loopback-connector-postgresql/releases/tag/v3.0.1):

> * Add docker setup (#256) (Sakib Hasan)
> * Allow explicit numeric datatype (#254) (Sakib Hasan)
> * Allow non-id serial properties (#198) (zbarbuto)
> * Revert PR #246 (#248) (Sakib Hasan)
> * Add loopback-connector as peer dependencies (#246) (Russ Tyndall)
> * Fix operations on ended transactions (zbarbuto)
> * dbdefaults: Cleanup InvalidDefault def after test (Kevin Delisle)
>  * Reuse the data source to avoid too many clients (Raymond Feng)

I guess https://github.com/strongloop/loopback-connector-postgresql/pull/230 may be the cause of this regression?

@raymondfeng @jannyHou @zbarbuto @kjdelisle could you PTAL?

**Comment by kjdelisle** [comment] 2017-06-26 16:34
As a stop-gap for now, I'll mark 3.0.0 as the latest release.
Once we confirm, we'll deprecate 3.0.1 to inform users about this version.

**Comment by dhmlau** [comment] 2017-06-26 18:01
I can reproduce it using `master`, but not `@2.8.0`

**Comment by zbarbuto** [comment] 2017-06-26 22:32
What does `this` refer to in the above context? Would it be possible to get a sandbox to reproduce the issue?

I just wrote a test for updateAll which is working fine for me but that's using Transaction and the model directly.

https://github.com/zbarbuto/loopback-connector-postgresql/commit/23d7a05dd1b6dc3f5566dd4c16d4fbd41263600e

**Comment by dhmlau** [comment] 2017-06-27 01:53
I was able to reproduce by adding a js file under `boot` folder:
```
'use strict';

module.exports = function(app) {
  var customer = app.models.Customer;
  customer.beginTransaction('READ COMMITTED', (err, tx)=>{
    customer.updateAll({name: 'aaa'}, {name: 'bbb'}, {transaction: tx}, (err)=>{
      console.log('err = ', err);
    });
  });
};
```

The error message `Transaction is not active` is coming from this line: https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/postgresql.js#L203.  For some reason, `transaction.txId`, once was set, is undefined.

**Comment by zbarbuto** [comment] 2017-06-27 23:08
Thanks for the steps. Have submitted a PR fix: #268

**Comment by dhmlau** [comment] 2017-06-28 13:30
connected to strongloop/loopback-connector-postgresql/pull/268

**Comment by dhmlau** [comment] 2017-07-14 15:53
Fixed in PR: https://github.com/strongloop/loopback-connector/pull/109

**Closed** 2017-07-17 15:14 UTC
Labels: bug, critical, team-apex, to-be-released
