### ISSUE TITLE
Error: Timeout in connecting after 5000 ms for pg 

### ISSUE THREAD

**Issue by transedward** [strongloop/loopback-connector-postgresql#77] opened 2015-05-11 08:58 UTC
g0v/ppt#6

It's weird that tables and all row are already constructed, however when I send request(using explorer):
it got this error, even if it's in localhost
{
"error": {
"name": "Error",
"status": 500,
"message": "Timeout in connecting after 5000 ms",
"stack": "Error: Timeout in connecting after 5000 ms\n at [object Object]. (/Users/mac/GitHub/edward_ptt/node_modules/loopback-datasource-juggler/lib/datasource.js:2029:10)\n at [object Object]._onTimeout (/Users/mac/GitHub/edward_ptt/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)\n at Timer.listOnTimeout (timers.js:89:15)"
}
}

any possible reason or suggestion?

**Comment by transedward** [comment] 2015-05-14 14:28
Today, I tired it again.
when I use autoupdate in server/boot/mock-data.js, all the get methods work
but if I change to automigrate, then the same error happens again.

**Comment by wiredots01** [comment] 2015-05-25 11:35
im also getting same error. is there an update for the fix?

**Comment by transedward** [comment] 2015-05-25 15:36
not yet, still have no idea of the error coming from

**Comment by geekguy** [comment] 2015-11-15 17:00
@transedward Any update here?

**Comment by jreidal** [comment] 2016-01-20 20:25
I just ran into the same problem when using automigrate.

**Comment by raymondfeng** [comment] 2016-01-20 22:48
Can you turn on debugging with env var `DEBUG=loopback:connector:postgresql` to see what's going on?

**Comment by jreidal** [comment] 2016-01-21 11:31
@raymondfeng Hi, having reviewed the debug log it seems to be my own doing (why am I not surprised ;-) This issue initially seemed to fit the bill, but it turned out I was not experiencing the same problem as @transedward. Sorry for the inconvenience.

**Comment by Narrator** [comment] 2016-02-03 06:47
I've been facing the same issue. Happens multiple times everyday. Any word on this one?

**Comment by cdock1029** [comment] 2016-02-15 20:00
Had this same issue. I was calling 
```js
app.dataSources.postgres.disconnect();
```
at the end of the automigrate callback. But of course this is disconnecting the database from your running app! So in server/boot/ files, don't disconnect.

**Comment by dancingshell** [comment] 2016-05-09 18:19
@Freakthemighty this may be causing the server timeouts on deployment https://github.com/strongloop/loopback-connector-postgresql/issues/77#issuecomment-184365157

**Comment by ketansp** [comment] 2016-08-04 16:43
I am facing same issue. Any solutions yet?

**Comment by 0candy** [comment] 2016-10-11 17:55
Could someone provide a sample repo to reproduce the issue with?
http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by viniciusgomes** [comment] 2016-12-23 18:51
Guys same issue, but at my local just run, slc run and works

**Comment by ssh24** [comment] 2017-07-12 16:20
It is no longer an issue with the latest postgresql connector.

**Dependency tree**:
```bash
sakibs-mac:postgresql-77 ssh$ npm ls --depth 0
postgresql-template@1.0.0 /Users/ssh/workspace/sandbox/loopback-sandbox/apps/postgresql/postgresql-77
├── compression@1.6.2
├── cors@2.8.3
├── eslint@3.19.0
├── eslint-config-loopback@8.0.0
├── helmet@1.3.0
├── loopback@3.8.5
├── loopback-boot@2.24.3
├── loopback-component-explorer@4.2.2
├── loopback-connector-postgresql@3.0.1
├── nsp@2.6.3
├── serve-favicon@2.4.3
└── strong-error-handler@2.1.1
```

Here is a sample reproduction:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.postgresqlDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo',
            age: 12
        }, {
            name: 'Bar',
            age: 25
        }, {
            name: 'Baz'
        }], function (err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            db.autoupdate(function(err) {
                if (err) throw err;

                console.log('\nAutoupdate complete');
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:postgresql-77 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { name: 'Foo', age: 12, id: 1 },
  { name: 'Bar', age: 25, id: 2 },
  { name: 'Baz', id: 3 } ]

Autoupdate complete
```

Closing this issue as it is not a bug anymore. Feel free to reopen if needed.

**Closed by ssh24** 2017-07-12 16:20 UTC
Labels: team-apex

**Comment by Harry97** [comment] 2018-05-19 22:29
Sadly, it's a problem for mongodb 
```
Unhandled rejection Error: Timeout in connecting after 5000 ms
    at Timeout._onTimeout (/home/harry/Projects/my-project/node_modules/loopback-datasource-juggler/lib/datasource.js:2529:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
```
"dependencies": {
    "base64-to-uint8array": "^1.0.0",
    "buffer": "^5.1.0",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "express-jwt": "^5.3.1",
    "file-type": "^7.7.1",
    "helmet": "^3.12.1",
    "jsonwebtoken": "^8.2.1",
    "lodash": "^4.17.4",
    "loopback": "^3.19.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.0.1",
    "loopback-component-storage": "^3.3.1",
    "loopback-connector-mongodb": "^3.4.3",
    "moment": "^2.22.1",
    "nodemon": "^1.17.4",
    "serve-favicon": "^2.5.0",
    "simpl-schema": "^1.4.2",
    "strong-error-handler": "^2.0.0",
    "underscore.string": "^3.3.4"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-loopback": "^10.0.0",
    "eslint-plugin-prettier": "^2.6.0",
    "nsp": "^3.2.1",
    "prettier": "^1.11.1",
    "prettierrc": "0.0.0-5"
  }
```
I tried updating most of my packages and double checked the datasource configurations. Also, I tried to directly connect to mongodb and had no problems at all. But it's worth noting that my mongodb version I'm currently running is 3.6.3 which is the latest version I presume.

datasource.json
```
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "MongoDS": {
    "name": "MongoDS",
    "connector": "mongodb",
    "url": "mongodb://localhost:27017/middleware"
  },
  "fileStorage": {
    "name": "fileStorage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./server/containers"
  }
}
```

**Comment by juanantoniodamianv** [comment] 2021-01-16 22:36
I have the same issue only in node >14, works fine on 12 lts.
